# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.Coursenames'),
        ),
    ]
